# Specify the node base image with your desired version, e.g. node:<version>
FROM alpine:3.18.3


# Set and create the working directory for this app
WORKDIR /client

# Copy this application's files from the current directory to the filesystem
# of the container at /app
COPY . /client


# Make the container accept traffic on port 3000 at runtime from other
# containers or the host if also published
EXPOSE 3000

# Run this shell command at build time
RUN npm install 

# Start the application
CMD npm start